name: grade-mp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: grade
      run: |
        cd cpp/cs598/ascii 
        chmod +x ./run.sh
        chmod +x ./build_arrow.sh
        chmod +x ./build_example.sh
        docker-compose run grade